/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/BasicDonut.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Light"
          position={[0.5, 0.4, -0.1]}
          rotation={[1.9, 0.9, -2]}
          userData={{ name: "Light" }}
        />
        <group
          name="Camera"
          position={[0.5, 0.4, 0.6]}
          rotation={[1.2, 0.3, -0.7]}
          userData={{ name: "Camera" }}
        />
        <mesh
          name="Donut"
          castShadow
          receiveShadow
          geometry={nodes.Donut.geometry}
          material={materials["Material.003"]}
          position={[0, 0, 0]}
          userData={{ name: "Donut" }}
        >
          <mesh
            name="Icing"
            castShadow
            receiveShadow
            geometry={nodes.Icing.geometry}
            material={materials["Material.002"]}
            userData={{ name: "Icing" }}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/BasicDonut.glb");
